# Services definition for building & deploying

services:

  chown:
    # Build
    image: ${IMAGES_PREFIX:-app}:${IMAGES_TAG:-latest}
    build:
      context: ./chown
      dockerfile: ./Dockerfile
      target: app_prod
    # Deploy
    environment:
      UID: ${UID:-1000}
      VOLUMES: ''
